L2_loss: false
batch_size: 2
channels: 64
condition_types:
- CT
- t2
- linespace
- linespace
- linespace
conditional: true
conditional_channel_size: 4
config: config/3D/SpineGAN_CT_T2_diffusion_img.conf
cpu: false
dataset: spinegan_T2w_3D
dataset_val: null
dim_multiples: 1, 2, 4, 8
exp_name: dif_spinegan3D_T2_CT_img
flip: true
gpus:
- 0
image_dropout: 0.0
image_mode: true
in_channel: 1
lambda_ssim: 0.0
learned_variance: false
learning_type: null
legacy_reload: true
linear: false
logs_folder: logs_diffusion3D
lr: 2.0e-05
max_epochs: 50000
model_name: unet
new: true
normalize:
  mean:
  - 0.5
  std:
  - 0.5
num_cpu: 16
num_validation_images: 1
output_channels: 1
prevent_nan: false
size: 256
size_w: -1
start_epoch: 0
target_shape3D:
- 32
- 128
- 128
timesteps: 1000
transform: crop
transpose_preview: true
volumes: true
